import type { Venue, Event, Post, CheckIn } from '../types';

export const mockVenues: Venue[] = [
  {
    id: '1',
    slug: 'uncle-dee-barber',
    name: "Uncle Dee's Barbershop",
    category: 'Barbershop',
    description: 'The freshest cuts in Soweto. Fades, lineups, and good vibes since 2009.',
    address: '14 Vilakazi Street',
    neighborhood: 'Orlando West',
    city: 'Soweto',
    checkinCount: 1243,
    followerCount: 389,
    isOpen: true,
    openHours: 'Mon–Sat 8am–7pm',
    tags: ['fades', 'lineups', 'beard trim', 'walk-ins welcome'],
    createdAt: '2024-01-10T08:00:00Z',
  },
  {
    id: '2',
    slug: 'mama-zulu-shisanyama',
    name: "Mama Zulu's Shisanyama",
    category: 'Shisanyama',
    description: 'Wood-fired braai, cold quarts, and the best pap in Khayelitsha. Open every weekend.',
    address: '3 Mew Way',
    neighborhood: 'Site B',
    city: 'Khayelitsha',
    checkinCount: 2871,
    followerCount: 754,
    isOpen: true,
    openHours: 'Fri–Sun 12pm–10pm',
    tags: ['braai', 'pap', 'wors', 'cold quarts', 'live music'],
    createdAt: '2024-02-15T10:00:00Z',
  },
  {
    id: '3',
    slug: 'corner-spaza-alex',
    name: 'Sipho Corner Spaza',
    category: 'Spaza Shop',
    description: 'Everything you need, open till late. Airtime, groceries, bread, and a cold Coke.',
    address: '78 London Road',
    neighborhood: 'Wynberg',
    city: 'Alexandra',
    checkinCount: 4102,
    followerCount: 203,
    isOpen: true,
    openHours: 'Daily 6am–11pm',
    tags: ['airtime', 'groceries', 'cold drinks', 'open late'],
    createdAt: '2024-01-05T06:00:00Z',
  },
  {
    id: '4',
    slug: 'glow-up-salon-mitchells',
    name: 'Glow Up Hair & Beauty',
    category: 'Salon',
    description: 'Braids, locs, relaxers, and facials. Walk in looking regular, leave looking blessed.',
    address: '22 Turfhall Road',
    neighborhood: 'Turfhall',
    city: "Mitchell's Plain",
    checkinCount: 987,
    followerCount: 461,
    isOpen: false,
    openHours: 'Tue–Sat 9am–6pm',
    tags: ['braids', 'locs', 'relaxer', 'facials', 'nails'],
    createdAt: '2024-03-01T09:00:00Z',
  },
  {
    id: '5',
    slug: 'faith-assembly-thokoza',
    name: 'Faith Assembly Church',
    category: 'Church',
    description: 'A community of believers in the heart of Thokoza. Sunday service, youth group, and prayer nights.',
    address: '5 Khumalo Street',
    neighborhood: 'Thokoza',
    city: 'Ekurhuleni',
    checkinCount: 3340,
    followerCount: 892,
    isOpen: false,
    openHours: 'Sun 9am–12pm | Wed 6pm–8pm',
    tags: ['sunday service', 'youth', 'prayer', 'community'],
    createdAt: '2023-11-20T07:00:00Z',
  },
  {
    id: '6',
    slug: 'spark-tutoring-mamelodi',
    name: 'Spark Tutoring Centre',
    category: 'Tutoring',
    description: 'Maths, Science, and English tutoring for Grades 8–12. Small groups, big results.',
    address: '11 Makgatho Drive',
    neighborhood: 'Mamelodi East',
    city: 'Pretoria',
    checkinCount: 612,
    followerCount: 278,
    isOpen: true,
    openHours: 'Mon–Fri 3pm–7pm | Sat 9am–2pm',
    tags: ['maths', 'science', 'english', 'grade 8-12', 'matric'],
    createdAt: '2024-02-01T12:00:00Z',
  },
];

export const mockEvents: Event[] = [
  {
    id: 'e1',
    venueId: '2',
    title: 'Heritage Day Mega Braai',
    description: 'Celebrate Heritage Day with us. Live music, competitions, and the biggest fire of the year.',
    startsAt: '2025-09-24T12:00:00Z',
    endsAt: '2025-09-24T22:00:00Z',
    isFree: false,
    price: 50,
    createdAt: '2025-09-01T10:00:00Z',
  },
  {
    id: 'e2',
    venueId: '1',
    title: 'Back to School Cut Special',
    description: 'R80 fades for kids under 16 all of January. Show your school schedule at the door.',
    startsAt: '2025-01-06T08:00:00Z',
    endsAt: '2025-01-31T19:00:00Z',
    isFree: false,
    price: 80,
    createdAt: '2025-01-01T08:00:00Z',
  },
  {
    id: 'e3',
    venueId: '5',
    title: 'Youth Night: Open Mic',
    description: 'Speak, sing, rap, or just show up. A safe space for the youth to express.',
    startsAt: '2025-07-19T18:00:00Z',
    endsAt: '2025-07-19T21:00:00Z',
    isFree: true,
    createdAt: '2025-07-10T10:00:00Z',
  },
  {
    id: 'e4',
    venueId: '6',
    title: 'Matric Exam Bootcamp',
    description: 'Intensive 3-day Maths and Science prep. Limited to 15 learners.',
    startsAt: '2025-10-20T09:00:00Z',
    endsAt: '2025-10-22T15:00:00Z',
    isFree: false,
    price: 350,
    createdAt: '2025-09-15T08:00:00Z',
  },
];

export const mockPosts: Post[] = [
  {
    id: 'p1',
    venueId: '2',
    authorId: 'u1',
    authorName: 'Thabo M.',
    content: "Mama Zulu's on a Saturday is not a vibe, it's a lifestyle. Already on my third quart 😤🔥",
    likeCount: 47,
    commentCount: 12,
    createdAt: '2025-04-12T15:30:00Z',
  },
  {
    id: 'p2',
    venueId: '1',
    authorId: 'u2',
    authorName: 'Lerato K.',
    content: 'Uncle Dee gave me the cleanest lineup I\'ve ever had. No cap. R120 well spent 💈',
    likeCount: 33,
    commentCount: 5,
    createdAt: '2025-04-10T11:00:00Z',
  },
  {
    id: 'p3',
    venueId: '4',
    authorId: 'u3',
    authorName: 'Nomsa P.',
    content: 'Came in with a broken heart and bad hair. Left with box braids and confidence restored 💅',
    likeCount: 89,
    commentCount: 21,
    createdAt: '2025-04-08T14:00:00Z',
  },
  {
    id: 'p4',
    venueId: '6',
    authorId: 'u4',
    authorName: 'Siphamandla D.',
    content: 'Failed Maths last term. After 3 months at Spark, I got 74% in my trial exam. These tutors are different 📚',
    likeCount: 102,
    commentCount: 18,
    createdAt: '2025-04-05T09:00:00Z',
  },
  {
    id: 'p5',
    venueId: '3',
    authorId: 'u5',
    authorName: 'Ayanda T.',
    content: 'Sipho at the corner has everything. Asked for Simba chips and a prepaid meter token at 10pm — delivered 💪',
    likeCount: 56,
    commentCount: 8,
    createdAt: '2025-04-03T22:00:00Z',
  },
  {
    id: 'p6',
    venueId: '5',
    authorId: 'u6',
    authorName: 'Pastor Bongani',
    content: 'Sunday service was electric today. The youth choir brought the whole building to its feet. God is good 🙏',
    likeCount: 74,
    commentCount: 30,
    createdAt: '2025-04-06T13:00:00Z',
  },
];

export const mockCheckIns: CheckIn[] = [
  { id: 'c1', venueId: '2', userId: 'u1', userName: 'Thabo M.', note: 'Here every Saturday!', createdAt: '2025-04-12T15:00:00Z' },
  { id: 'c2', venueId: '1', userId: 'u2', userName: 'Lerato K.', note: 'Lineup day 💈', createdAt: '2025-04-10T10:30:00Z' },
  { id: 'c3', venueId: '3', userId: 'u5', userName: 'Ayanda T.', createdAt: '2025-04-03T21:55:00Z' },
  { id: 'c4', venueId: '5', userId: 'u6', userName: 'Pastor Bongani', note: 'Sunday service', createdAt: '2025-04-06T09:00:00Z' },
];
